# Site settings
title: SiriusCrain's portfolio
description: SiriusCrain's works
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: SiriusCrain
user_description: Just another programmer
user_title: Software Developer
email: siriuscrain@gmail.com
twitter_username: SiriusCrain
github_username:  SiriusCrain


exclude: ['package.json', 'src' , 'node_modules']
